# Generated by Django 4.0.4 on 2022-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40)),
                ('version', models.TextField(max_length=10)),
                ('map_zip_file', models.FileField(blank=True, upload_to='uploads/map/origins')),
            ],
        ),
    ]
