# Generated by Django 4.0.4 on 2022-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermanager',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='servermanager',
            name='version',
            field=models.CharField(max_length=10),
        ),
    ]
