# Generated by Django 4.0.4 on 2022-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0002_alter_servermanager_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermanager',
            name='is_server_running',
            field=models.BooleanField(default=False),
        ),
    ]
